name: puma
channels: [conda-forge]
dependencies:
  - python=3.11
  - pip
  - numpy>=1.25
  - tqdm
  - einops
  - pyyaml
  - packaging
  - matplotlib
  - pip:
    - transformers
    - datasets
    - huggingface-hub
    - wandb
    - pytorch-lightning
    - omegaconf